// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9OcS-Iwp4i8_tJclKapV3TTYeWqziwSQ',
    appId: '1:628240924231:web:23292fae267d9c625cbb62',
    messagingSenderId: '628240924231',
    projectId: 'plazas-project',
    authDomain: 'plazas-project.firebaseapp.com',
    storageBucket: 'plazas-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8mJ8QviylsYZPDejcC3Z0MheWAOadnPI',
    appId: '1:628240924231:android:9f227851576fcb385cbb62',
    messagingSenderId: '628240924231',
    projectId: 'plazas-project',
    storageBucket: 'plazas-project.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUZzufqI_9rYt8kUqtVFWC8gW3vhEp6fg',
    appId: '1:628240924231:ios:8b99d6465a30b4895cbb62',
    messagingSenderId: '628240924231',
    projectId: 'plazas-project',
    storageBucket: 'plazas-project.firebasestorage.app',
    iosBundleId: 'com.amdp.firefly.plazas',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUZzufqI_9rYt8kUqtVFWC8gW3vhEp6fg',
    appId: '1:628240924231:ios:8b99d6465a30b4895cbb62',
    messagingSenderId: '628240924231',
    projectId: 'plazas-project',
    storageBucket: 'plazas-project.firebasestorage.app',
    iosBundleId: 'com.amdp.firefly.plazas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9OcS-Iwp4i8_tJclKapV3TTYeWqziwSQ',
    appId: '1:628240924231:web:2487c3544d0d78cc5cbb62',
    messagingSenderId: '628240924231',
    projectId: 'plazas-project',
    authDomain: 'plazas-project.firebaseapp.com',
    storageBucket: 'plazas-project.firebasestorage.app',
  );
}
